Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('home/', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

Ecommerce/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('activate/<str:email_token>/', views.activate_email, name='activate'),
]

Ecommerce/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('category/', views.category, name='category'),
    path('clients/', views.clients, name='clients'),
    path('contact/', views.contact, name='contact'),
    path('products/', views.products, name='products'),
    
]

Ecommerce/products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('details/<slug>/', views.details, name='details'),
]

Ecommerce/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from base.models import BaseModel
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from base.emails import send_account_activation_email

class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    is_email_verified = models.BooleanField(default=False)
    email_token = models.CharField(max_length=100, null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile')
    
    
@receiver(post_save, sender = User)
def send_email_token(sender, instance, created, **kwargs):
    try:
        if created:
            email_token = str(uuid.uuid4())
            Profile.objects.create(user = instance, email_token = email_token) 
            email = instance.email
            send_account_activation_email(email, email_token)
    except Exception as e:
        print(e)

Ecommerce/base/models.py
from django.db import models
import uuid


class BaseModel(models.Model):
    uid = models.UUIDField(primary_key=True, editable = False, default = uuid.uuid4)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        abstract = True

Ecommerce/home/models.py
from django.db import models

# Create your models here.

Ecommerce/products/models.py
from django.db import models
from base.models import BaseModel
from django.utils.text import slugify

class Category(BaseModel):
    category_name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    category_image = models.ImageField(upload_to="categories")
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)
        
    def __str__(self) -> str:
        return self.category_name
    
class Product(BaseModel):
    product_name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    price = models.IntegerField()
    product_description = models.TextField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.product_name)
        super(Product, self).save(*args, **kwargs)
        
    def __str__(self) -> str:
        return self.product_name
    
class ProductImage(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_images")
    image = models.ImageField(upload_to="product")

Ecommerce/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from .models import Profile

def register_page(request):
    
    if request.method == 'POST':
        first_name = request.POST.get('name')
        last_name = ''
        email = request.POST.get('email')
        password = request.POST.get('password')
    
        user_obj = User.objects.filter(username = email)
    
        if user_obj.exists():
            messages.warning(request, 'Email is already taken.')
            return HttpResponseRedirect(request.path_info)
    
        user_obj = User.objects.create(first_name = first_name, last_name = last_name, email = email, username = email)
        user_obj.set_password(password)
        user_obj.save()
        
        messages.success(request, 'An email has been sent on your mail')
        messages.warning(request, "If you can't find the email, please check the spam folder")
        
        return HttpResponseRedirect(request.path_info)
    
    return render(request, 'accounts/registration.html')

def login_page(request):
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
    
        user_obj = User.objects.filter(username = email)
    
        if not user_obj.exists():
            messages.warning(request, 'User Not Found.')
            return HttpResponseRedirect(request.path_info)
        
        if not user_obj[0].profile.is_email_verified:
            messages.warning(request, 'Account Not Verified.')
            return HttpResponseRedirect(request.path_info)
        
        user_obj = authenticate(username = email, password = password)
        

        if user_obj:
            login(request, user_obj)
            return redirect("http://127.0.0.1:8000/")
         
        messages.warning(request, 'Invalid Email or Password')
        return HttpResponseRedirect(request.path_info)

    return render(request, 'accounts/login.html')

def activate_email(request, email_token):
    try:
        
        user = Profile.objects.get(email_token= email_token)
        user.is_email_verified = True
        user.save()
        return redirect("http://127.0.0.1:8000/accounts/login")
    except Exception as e:
        return HttpResponse('Invalid Email Token')

Ecommerce/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from products.models import Product
from django.contrib import messages

def index(request):
    context = {'products' : Product.objects.all()}
    return render(request, 'home/index.html', context )

def category(request):
    return render(request, 'home/category.html') 

def clients(request):
    return render(request, 'home/clients.html') 

def products(request):
    context = {'products' : Product.objects.all()}
    return render(request, 'home/products.html', context) 

def contact(request):
    return render(request, 'home/contact.html') 

Ecommerce/products/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product

def details(request, slug):
    context = {'products' : Product.objects.all().filter(slug=slug)}
    return render(request, 'products/details.html', context)

Ecommerce/templates/accounts/login.html
{% extends "base/base.html" %}
{%load static%}
{% block 'title' %}Login - E-Commerce{% endblock %}
{%block 'cssFile' %}{%endblock%}
{% block 'banner' %}
<div class="container" style="background-color: transparent;">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center mb-4">Login to your  Account</h2>
                    <form id="registrationForm" method="POST">
                        {% csrf_token %}
                        {% include "base/alert.html" %}
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email" required class="form-control" id="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" required class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                    <p class="text-center mt-3">Don't have an account? <a href="{%url 'accounts:register'%}">Register</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block 'jsFile' %}{% endblock %}

Ecommerce/templates/accounts/registration.html
{% extends "base/base.html" %}
{%load static%}
{% block 'title' %}Registration - E-Commerce{% endblock %}
{%block 'cssFile' %}{%endblock%}
{% block 'banner' %}
<div class="container" style="background-color: transparent;">
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center mb-4">Create an Account</h2>
                    <form id="registrationForm" method="POST">
                        {% csrf_token %}
                        {% include 'base/alert.html' %}
                        <div class="form-group">
                            <label for="username">Name:</label>
                            <input type="text" required class="form-control" id="username" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email" required class="form-control" id="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" required class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </form>
                    <p class="text-center mt-3">Already have an account? <a href="{%url 'accounts:login' %}">Login</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block 'jsFile' %}{% endblock %}

Ecommerce/templates/base/alert.html
{% if messages %}
{% for message in messages %}

    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
   {{ message }}
    </div>
    {% endfor %}
    
{% endif %}

Ecommerce/templates/base/base.html
{%load static%}

<!DOCTYPE html>
<html>

<head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas --> 
    <title>{% block 'title' %}{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- owl carousel style -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets --> 
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block 'cssFile' %}{% endblock %}
  
  </head>

    <body>

      <!--header section start -->
<div class="header_section">
    <div class="container">
       <nav class="navbar navbar-dark bg-dark">
          <a class="logo" href="{% url 'home:index' %}"><img src="{% static 'images/logo.png' %}"></a>
          <div class="search_section">
             <ul>
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="#"><img src="{% static 'images/shopping-bag.png' %}"></a></li>
                <li><a href="{% url 'home:category' %}"><img src="{% static 'images/search-icon.png' %}"></a></li>
             </ul>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarsExample01">
             <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                   <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{% url 'home:category' %}">Category</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{% url 'home:products' %}">Products</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{% url 'home:clients' %}">Client</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a>
                </li>
             </ul>
          </div>
       </nav>
    </div>
    {% block 'banner' %} {% endblock %}
  </div>
  <!--header section end -->
        

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
      {% block 'content' %}{% endblock %}



      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      {% block 'jsFile' %}{% endblock %}


      <!-- footer section start -->
      <div class="footer_section layout_padding">
        <div class="container">
           <div class="row">
              <div class="col-lg-6 col-sm-12">
                 <h4 class="information_text">Category</h4>
                 <p class="dummy_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim </p>
              </div>
              <div class="col-lg-3 col-sm-6">
                 <div class="information_main">
                    <h4 class="information_text">Useful Links</h4>
                    <p class="many_text">Contrary to popular belief, Lorem Ipsum is not simply random text. It </p>
                 </div>
              </div>
              <div class="col-lg-3 col-sm-6">
                 <div class="information_main">
                    <h4 class="information_text">Contact Us</h4>
                    <p class="call_text"><a href="#">+01 1234567890</a></p>
                    <p class="call_text"><a href="#">+01 9876543210</a></p>
                    <p class="call_text"><a href="#">demo@gmail.com</a></p>
                    <div class="social_icon">
                       <ul>
                          <li><a href="#"><img src="{% static 'images/fb-icon.png' %}"></a></li>
                          <li><a href="#"><img src="{% static 'images/twitter-icon.png' %}"></a></li>
                          <li><a href="#"><img src="{% static 'images/linkedin-icon.png' %}"></a></li>
                          <li><a href="#"><img src="{% static 'images/instagram-icon.png' %}"></a></li>
                       </ul>
                    </div>
                 </div>
              </div>
           </div>
           <div class="copyright_section">
              <h1 class="copyright_text">
              Copyright 2023 All Right Reserved</h1>
           </div>
        </div>
      </div>
      <!-- footer section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <!-- javascript --> 
      <script src="{% static 'js/owl.carousel.js' %}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script> 
      <script type="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2//2.0.0-beta.2.4/owl.carousel.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="{% static '../../assets/js/vendor/popper.min.js' %}"></script>
      <script src="{% static '../../dist/js/bootstrap.min.js' %}"></script>
   </body>
</html>

Ecommerce/templates/home/index.html
{%extends "base/base.html"%}
{% load static %}


{% block 'cssFile' %} {% endblock%}
{% block 'title' %}Home - Ecommerce{% endblock%}
{% block 'banner' %}
{%include "base/banner.html" %}
{% endblock %}
{% block 'content' %}
         
      <!--category section start -->
      <div class="container">
         <div class="category_section">
            <div class="row">
               <div class="col-lg-2 col-sm-12">
                  <h1 class="category_text">Category</h1>
               </div>
               <div class="col-lg-10 col-sm-12 main">
                  <div class="col">
                     <div class="box_main">
                        <div class="icon_1"></div>
                        <h4 class="fashion_text active">New Fashion</h4>
                     </div>
                  </div>
                  <div class="col">
                     <div class="box_main">
                        <div class="icon_2"></div>
                        <h4 class="fashion_text">Clothing</h4>
                     </div>
                  </div>
                  <div class="col">
                     <div class="box_main">
                        <div class="icon_3"></div>
                        <h4 class="fashion_text">Watches</h4>
                     </div>
                  </div>
                  <div class="col">
                     <div class="box_main">
                        <div class="icon_4"></div>
                        <h4 class="fashion_text">Accessories</h4>
                     </div>
                  </div>
                  <div class="col">
                     <div class="box_main">
                        <div class="icon_5"></div>
                        <h4 class="fashion_text">Sweaters & Jackets</h4>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="category_section_2">
            <div class="row">
               <div class="col-lg-4 col-sm-12">
                  <div class="beds_section active">
                     <h1 class="bed_text">Up to 50% off | Beds</h1>
                     <div><img src="{% static 'images/img-2.png' %}" class="image_2"></div>
                     <div class="seemore_bt"><a href="{% url 'home:category' %}">see More</a></div>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="beds_section">
                     <h1 class="bed_text">organized in style</h1>
                     <div><img src="{% static 'images/img-3.png' %}" class="image_2"></div>
                     <div class="seemore_bt"><a href="{% url 'home:category' %}">see More</a></div>
                  </div>
               </div>
               <div class="col-lg-4 col-sm-12">
                  <div class="beds_section">
                     <h1 class="bed_text">Refurbished mixer</h1>
                     <div><img src="{% static 'images/img-4.png' %}" class="image_2"></div>
                     <div class="seemore_bt"><a href="{% url 'home:category' %}">see More</a></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- category section end -->
      <!-- beauty product section start -->
      <div class="beauty_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-lg-4 col-sm-12">
                  <div class="beauty_box">
                     <h1 class="bed_text">Beauty products</h1>
                     <div><img src="{% static 'images/img-5.png' %}" class="image_3"></div>
                     <div class="seemore_bt"><a href="{% url 'home:category' %}">see More</a></div>
                  </div>
               </div>
               <div class="col-lg-8 col-sm-12">
                  <div class="beauty_box_1">
                     <h1 class="bed_text_1">Explore trending electronics</h1>
                     <div><img src="{% static 'images/img-6.png' %}" class="image_3"></div>
                     <div class="seemore_bt_1"><a href="{% url 'home:category' %}">see More</a></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- beauty product section end -->
      <!-- product section start -->
      <div class="product_section layout_padding">
         <div class="container">
            <h1 class="feature_taital">FEATURED PRODUCTS</h1>
            <p class="feature_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking</p>
            <div class="product_section_2">
               <div class="row">
                  <div class="col-sm-12">
                     
                     
                     {% for product in products %}
                     
                        <div class="feature_box mb-4">
                           <a href="{%url 'products:details' slug=product.slug %}">
                           <h1 class="readable_text">{{product.product_name}}</h1>
                           <h3>Rs. {{product.price}}</h3>
                           <div><img src="/media/{{ product.product_images.first.image }}" class="image_7"></div> 
                           </a>
                           <div class="seemore_bt"><a href="{% url 'home:products' %}">see More</a></div>
                        </div>
                     
                     {% endfor %}
                     
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- product section end -->
      <!-- client section start -->
      <div class="client_section layout_padding">
         <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="feature_taital">what is says our customer</h1>
                     <p class="feature_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking</p>
                     <div class="client_section_2">
                        <div class="image_9"><img src="{% static 'images/img-9.png' %}"></div>
                        <h3 class="nolmal_text">Normal distribution</h3>
                        <p class="ipsum_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                        <div class="image_9"><img src="{% static 'images/icon-10.png' %}"></div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="feature_taital">FEATURED PRODUCTS</h1>
                     <p class="feature_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking</p>
                     <div class="client_section_2">
                        <div class="image_9"><img src="{% static 'images/img-9.png' %}"></div>
                        <h3 class="nolmal_text">Normal distribution</h3>
                        <p class="ipsum_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                        <div class="image_9"><img src="{% static 'images/icon-10.png' %}"></div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="feature_taital">FEATURED PRODUCTS</h1>
                     <p class="feature_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking</p>
                     <div class="client_section_2">
                        <div class="image_9"><img src="{% static 'images/img-9.png' %}"></div>
                        <h3 class="nolmal_text">Normal distribution</h3>
                        <p class="ipsum_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                        <div class="image_9"><img src="{% static 'images/icon-10.png' %}"></div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class=""><img src="{% static 'images/left-icon.png' %}"></i>
            </a>
            <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class=""><img src="{% static 'images/right-icon.png' %}"></i>
            </a>
         </div>
      </div>
      <!-- client section end -->
      <!-- newsletter section start -->
      <div class="newsletter_section layout_padding">
         <div class="container">
            <h6 class="conect_text">Connect to caraft</h6>
            <h1 class="newsletter_taital">Join Our Newsletter</h1>
            <p class="newsletter_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration </p>
            <div class="input-group mb-3">
               <input type="text" class="form-control" placeholder="Enter your email" aria-label="Enter your email" aria-describedby="basic-addon2">
               <div class="input-group-append">
                  <span class="input-group-text" id="basic-addon2">Subscribe</span>
               </div>
            </div>
         </div>
      </div>
      <!-- newsletter section end -->
      
      

{% endblock %}
{% block 'jsFile' %} {% endblock%}

Ecommerce/templates/home/products.html
{%extends "base/base.html"%}
{% load static %}


{% block 'cssFile' %} {% endblock%}
{% block 'title' %}Products - Ecommerce{% endblock%}
{% block 'banner' %}
      <!-- product section start -->
      <div class="product_section layout_padding mb-5">
         <div class="container">
            <h1 class="feature_taital">FEATURED PRODUCTS</h1>
            <p class="feature_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking</p>
            <div class="product_section_2">
               <div class="row">
                  <div class="col-sm-12">
                     
                     
                     {% for product in products %}
                        <div class="feature_box mb-4">
                           <a href="{%url 'products:details' slug=product.slug %}">
                           <h1 class="readable_text">{{product.product_name}}</h1>
                           <h3>Rs. {{product.price}}</h3>
                           <div><img src="/media/{{ product.product_images.first.image }}" class="image_7"></div> 
                           </a>
                        <div class="seemore_bt"><a href="{% url 'home:category' %}">see More</a></div>
                     </div>
                     {%endfor%}
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- product section end -->
{% endblock %}
{% block 'jsFile' %} {% endblock%}